name: starter-app-development
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: sh -c "pnpm run dev"
    container_name: app-development
    depends_on:
      [nginx, redis]
    environment:
      APP_NAME: ${APP_NAME:-starter-app}
      APP_PORT: ${APP_PORT:-7270}
      VITE_TRPC_ENDPOINT: http://localhost:${APP_PORT:-7270}/trpc
    ports:
      - "${APP_PORT:-7270}:${APP_PORT:-7270}"
      # used by vite for hot module replacement
      - 24678:24678
    volumes:
      - ./src:/app/src
  nginx:
    container_name: nginx-development
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.development.conf:/etc/nginx/conf.d/default.conf
  redis:
    container_name: redis-development
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - db-volume:/data/db

volumes:
  db-volume: