
const bcp47ToNativeLanguageName = {
	'en-us': 'English (United States)',
	'es-us': 'Español (Estados Unidos)',
	'zh-cn': '中文（中国）',
	
	'ar-sa': 'العربية',
	'bg-bg': 'български',
	'bn-bd': 'বাংলা (বাংলাদেশ)',
	'bn-in': 'বাংলা (ভারত)',
	'bs-ba': 'Bosanski',
	'cs-cz': 'Čeština',
	'da-dk': 'Dansk',
	'de-de': 'Deutsch (Deutschland)',
	'el-gr': 'Ελληνικά (Ελλάδα)',
	'en-au': 'English (Australia)',
	'en-gb': 'English (United Kingdom)',
	'en-in': 'English (India)',
	'en-ng': 'English (Nigeria)',
	'es-419': 'Español (América Latina)',
	'es-es': 'Español (España)',
	'et-ee': 'Eesti',
	'fi-fi': 'Suomi',
	'fil-ph': 'Filipino',
	'fr-ca': 'Français (Canada)',
	'fr-fr': 'Français (France)',
	'gu-in': 'ગુજરાતી',
	'he-il': 'עברית ',
	'hi-in': 'हिन्दी (भारत)',
	'hr-hr': 'Hrvatski',
	'hu-hu': 'Magyar',
	'id-id': 'Bahasa Indonesia',
	'in-id': 'Bahasa Indonesia',
	'is-is': 'Íslenska',
	'it-it': 'Italiano',
	'iw-il': 'עברית ',
	'ja-jp': '日本語',
	'jv-id': 'Javanese',
	'km-kh': 'ភាសាខ្មែរ',
	'kn-in': 'ಕನ್ನಡ',
	'ko-kr': '한국어',
	'lt-lt': 'Lietuvių',
	'lv-lv': 'Latviešu',
	'ml-in': 'മലയാളം',
	'mr-in': 'मराठी',
	'ms-my': 'Bahasa Melayu',
	'nb-no': 'Norsk Bokmål',
	'ne-np': 'नेपाली',
	'nl-be': 'Nederlands (Belgium)',
	'nl-nl': 'Nederlands (Nederland)',
	'no-no': 'Norsk',
	'pa-in': 'ਪੰਜਾਬੀ',
	'pl-pl': 'Polski',
	'pt-br': 'Português (Brasil)',
	'pt-pt': 'Português (Portugal)',
	'ro-ro': 'Română',
	'ru-ru': 'Русский',
	'si-lk': 'සිංහල',
	'sk-sk': 'Slovenčina',
	'sq-al': 'Shqip',
	'su-id': 'Basa Sunda',
	'sv-se': 'Svenska',
	'sw-ke': 'Kiswahili',
	'ta-in': 'தமிழ்',
	'te-in': 'తెలుగు',
	'th-th': 'ไทย',
	'tr-tr': 'Türkçe',
	'uk-ua': 'Українська',
	'ur-pk': 'اُردُو',
	'vi-vn': 'Tiếng Việt',
	'yue-hk': '粵語（繁體）',
	'zh-hk': '中文（繁體）',
	'zh-mo': '中文（澳门）',
	'zh-sg': '中文（新加坡）',
	'zh-tw': '中文（台灣）',
};

export default bcp47ToNativeLanguageName;
